spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@localhost:27017/${MONGO_DB}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
# cloud:
#   aws:
#     credentials:
#       access-key: ${AWS_ACCESS_KEY}
#       secret-key: ${AWS_SECRET_KEY}
#     region:
#       static: ${AWS_REGION}
#     s3:
#       bucket: ${AWS_S3_BUCKET}
