spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_TEST_DATABASE:mysql_test}
    username: ${MYSQL_TEST_USER:${MYSQL_USER}}
    password: ${MYSQL_TEST_PASSWORD:${MYSQL_PASSWORD}}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@localhost:27017/${MONGO_TEST_DB:mongo_test}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

