spring:
  config:
    import:
      - optional:file:.env.test.properties
      - optional:file:.env.properties
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_TEST_DATABASE:mysql_test}
    username: ${MYSQL_TEST_USER:${MYSQL_USER:root}}
    password: ${MYSQL_TEST_PASSWORD:${MYSQL_PASSWORD:${MYSQL_ROOT_PASSWORD:rootpw}}}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@localhost:27017/${MONGO_TEST_DB:mongo_test}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

logging:
  level:
    org.hibernate.sql: debug
#    org.hibernate.orm.jdbc.bind: trace

minio:
  endpoint: http://localhost:9000
  access-key: minio-key
  secret-key: minio-secret
  bucket-name: test-bucket

cloud:
  aws:
    credentials:
      access-key: aws-key
      secret-key: aws-secret
    region:
      static: ap-northeast-2
    s3:
      bucket: test-bucket
